services:
  - type: web
    name: click-bothelp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker
    plan: free

